blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://wisebot.tk/support
    about: If you need help with the bot, or just need to ask some questions about how the bot works, please open a ticket in our Discord server for help.
